language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - node_modules
services:
  - postgresql
before_script:
  - psql -c 'create database casper_test;' -U postgres
script:
  - npm i -g sequelize-cli
  - npm ci
  - npm test
after_success:
  - npm run coveralls
notifications:
  email: false
