language: node_js
node_js:
  - "stable"
cache: npm
services:
  - postgresql
before_script:
  - psql -c 'create database travel_application_test;' -U postgres
script:
  - npm i -g sequelize-cli
  - npm ci
  - npm test
after_success:
  - npm run coverage
notifications:
  email: false
deploy:
  provider: heroku
  api_key:
    secure: "eGesMwZbY6n/CclV0YHjW7cnlaF67U2KSWkwMgF93eqmCUjf7Luf4/9vmyWMIjs1MgNEwQppg7yn774Q7O3wf6Dv5/4Sq19dBfQmCOGasvI/XuZZahnX597ndga35nUEPqKk9CciPQiFs9T6b+CpsAS3IwijjCCRdmoTY4sskPuP0fk3/jAmsUovpL70kFZUYfNeyrE6HY0pl6BDoeQjVuGtVcgRco1Eg8H5ofCZPDMdudM4axp9vaBZRyrq2y+adiHVoTTeWDbnfouubD+md/sTkp2HNzRcTkbzgfxm6Oo/CNTBXhmFgCY4nFtJyNUeGnnUewVtuWqtNsazevwoNGWhBsVWyVmE23j5V7JWj422wTuNikcEnYJHPdRA5U2MZCmBu1kkPowgk99wdA1EVBYm2Gv0XI43I3fFHcRh65noBYl0+CNwvWVslB5/h/5nWPrD+VgM2GTJgKLx5GHAVM4unmnXn6lIhIs0I6Ma7wtpexO8qaIKml1EknHhTg8YTZnJtlmjxt3qrbmC29nyzJ7EOVUDFddMY2rPbQZjQEtezuz5oCCPlIo0YkAjxww248SeL+pBAywbFtrpC+Oqz7B8k7u1L50uzAJW6LhZsCEIIxMRKZMebBOsoGuq/aui0Hxt9Tyxb7MzlP0X6wiReWCu1QdmoQUtE4kLljIUeO8="
  app:
    master: travel-application-production
    develop: travel-application-develop
  run:
    - npm run migrate
    - npm run seed
