version: "3"

services:
  web_api:
    build: .
    container_name: travel-application-backend
    volumes:
      - .:/usr/src/app
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    env_file:
      - .env

  postgres:
    container_name: travel-application-backend-database
    image: onjin/alpine-postgres:9.6
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      LC_ALL: C.UTF-8
      POSTGRES_USER: postgres
      POSTGRES_DB: travel-application
